// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDux50oaNosHIFOdWYRbTa21XpfWqU9JCw',
    appId: '1:728426062944:web:2351469e2a59e7d2704f05',
    messagingSenderId: '728426062944',
    projectId: 'tutornest-d30d7',
    authDomain: 'tutornest-d30d7.firebaseapp.com',
    storageBucket: 'tutornest-d30d7.firebasestorage.app',
    measurementId: 'G-CDY88ZKXY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc5uxBAWEG74xW7-J4EbTRyjaUeIjbU6E',
    appId: '1:728426062944:android:cd4b59df8e1a07a3704f05',
    messagingSenderId: '728426062944',
    projectId: 'tutornest-d30d7',
    storageBucket: 'tutornest-d30d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuQQB6ycnZ55CsjoegC1gLN-U0SmOsDxM',
    appId: '1:728426062944:ios:3c9858b94c52d435704f05',
    messagingSenderId: '728426062944',
    projectId: 'tutornest-d30d7',
    storageBucket: 'tutornest-d30d7.firebasestorage.app',
    iosBundleId: 'com.example.tutornest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuQQB6ycnZ55CsjoegC1gLN-U0SmOsDxM',
    appId: '1:728426062944:ios:3c9858b94c52d435704f05',
    messagingSenderId: '728426062944',
    projectId: 'tutornest-d30d7',
    storageBucket: 'tutornest-d30d7.firebasestorage.app',
    iosBundleId: 'com.example.tutornest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDux50oaNosHIFOdWYRbTa21XpfWqU9JCw',
    appId: '1:728426062944:web:be0ed4c4fba9105c704f05',
    messagingSenderId: '728426062944',
    projectId: 'tutornest-d30d7',
    authDomain: 'tutornest-d30d7.firebaseapp.com',
    storageBucket: 'tutornest-d30d7.firebasestorage.app',
    measurementId: 'G-CQL8Y7XGRR',
  );
}
